sonar.organization=x0uill3
sonar.projectKey=x0uill3_-RE-Source-BackOffice
sonar.projectVersion=1.0.0
sonar.language=js
sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,.github/**,Dockerfile*,nginx/**
sonar.qualityGate.wait=false
